title: Brian Pietracatella # your name (or website title) here
logo: "/images/circle2.png?raw=True" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently I am indepedently continuing my education and applying my knowledge to data science projects. 
  <br><br>
  I graduated with a Masters in Analytics from the Institute of Advanced Analytics in 2019
  <br><br>
  <a href="https://www.linkedin.com/in/brianpietracatella/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
